export const boardArea: string;
export const boardPos: string;
export const imgBoard: string;
export const pieceArea: string;
export const pieceSquareArea: string;
export const pointSquareArea: string;
export const imgPiece: string;
export const imgPieceNormal: string;
export const imgPieceSelected: string;
